spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/eleicao
    username: root
    password:

  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    exchange: subscription-notifications
    pauta-routing-key: subscription-pauta.routing-key

spring-doc:
  swagger-ui:
    path: /
    tagsSorter: alpha
    operationsSorter: method