spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/eleicao
    username: root
    password:

spring-doc:
  swagger-ui:
    path: /
    tagsSorter: alpha
    operationsSorter: method